#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Nanzhu

#include "Basic.hpp"

#include "ABP_BaseRole_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Nanzhu.ABP_Nanzhu_C
// 0x0000 (0x29750 - 0x29750)
class UABP_Nanzhu_C final : public UABP_BaseRole_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Nanzhu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Nanzhu_C")
	}
	static class UABP_Nanzhu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Nanzhu_C>();
	}
};
DUMPER7_ASSERTS_UABP_Nanzhu_C;

}

