#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActorManager

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ActorManager.BP_ActorManager_C
// 0x0000 (0x0030 - 0x0030)
class UBP_ActorManager_C final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActorManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActorManager_C")
	}
	static class UBP_ActorManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ActorManager_C>();
	}
};
DUMPER7_ASSERTS_UBP_ActorManager_C;

}

