#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cloud_None

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CloudPrefab_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Cloud_None.BP_Cloud_None_C
// 0x0008 (0x04D0 - 0x04C8)
class ABP_Cloud_None_C final : public ABP_CloudPrefab_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Cloud_None_C;                    // 0x04C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_Cloud_None(int32 EntryPoint);
	void EditorTick(float DeltaSeconds);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void Active();
	void Hidden();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Cloud_None_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Cloud_None_C")
	}
	static class ABP_Cloud_None_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cloud_None_C>();
	}
};
DUMPER7_ASSERTS_ABP_Cloud_None_C;

}

