#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MaterialControllerRenderActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MaterialControllerRenderActor.BP_MaterialControllerRenderActor_C
// 0x0018 (0x02C8 - 0x02B0)
class ABP_MaterialControllerRenderActor_C final : public AActor
{
public:
	class UCharRenderingComponent_C*              CharRenderingComponent;                            // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 RefActor;                                          // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MaterialControllerRenderActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MaterialControllerRenderActor_C")
	}
	static class ABP_MaterialControllerRenderActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MaterialControllerRenderActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_MaterialControllerRenderActor_C;

}

