#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Nanzhu_Seq_V2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SModelConfig_structs.hpp"


namespace SDK::Params
{

// Function BP_Nanzhu_Seq_V2.BP_Nanzhu_Seq_V2_C.UserConstructionScript
// 0x0468 (0x0468 - 0x0000)
struct BP_Nanzhu_Seq_V2_C_UserConstructionScript final
{
public:
	struct FSModelConfig                          CallFunc_GetDataTableRowFromName_OutRow;           // 0x0000(0x0448)(ContainsInstancedReference, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x0448(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsEditor_ReturnValue;                     // 0x0449(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_44A[0x6];                                      // 0x044A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                CallFunc_LoadAsset_Blocking_ReturnValue;           // 0x0450(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USkeletalMesh*                          K2Node_DynamicCast_As_____;                        // 0x0458(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0460(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_Nanzhu_Seq_V2_C_UserConstructionScript;

// Function BP_Nanzhu_Seq_V2.BP_Nanzhu_Seq_V2_C.SwitchMeshTransform
// 0x012C (0x012C - 0x0000)
struct BP_Nanzhu_Seq_V2_C_SwitchMeshTransform final
{
public:
	bool                                          LevelA;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult; // 0x0004(0x0094)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FHitResult                             CallFunc_K2_SetRelativeLocationAndRotation_SweepHitResult_1; // 0x0098(0x0094)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
DUMPER7_ASSERTS_BP_Nanzhu_Seq_V2_C_SwitchMeshTransform;

}

