#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Nvzhu_Seq_V2

#include "Basic.hpp"

#include "BP_BaseRole_Seq_V2_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Nvzhu_Seq_V2.BP_Nvzhu_Seq_V2_C
// 0x0000 (0x0388 - 0x0388)
class ABP_Nvzhu_Seq_V2_C final : public ABP_BaseRole_Seq_V2_C
{
public:
	void UserConstructionScript();
	void SwitchMeshTransform(bool LevelA);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Nvzhu_Seq_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Nvzhu_Seq_V2_C")
	}
	static class ABP_Nvzhu_Seq_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Nvzhu_Seq_V2_C>();
	}
};
DUMPER7_ASSERTS_ABP_Nvzhu_Seq_V2_C;

}

