#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SM_BindStateDelaySuicide

#include "Basic.hpp"

#include "SMSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SM_BindStateDelaySuicide.BP_SM_BindStateDelaySuicide_C
// 0x0008 (0x0038 - 0x0030)
class UBP_SM_BindStateDelaySuicide_C final : public UASMBindState
{
public:
	int32                                         SuicideDelay;                                      // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DestroyDelay;                                      // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SM_BindStateDelaySuicide_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SM_BindStateDelaySuicide_C")
	}
	static class UBP_SM_BindStateDelaySuicide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SM_BindStateDelaySuicide_C>();
	}
};
DUMPER7_ASSERTS_UBP_SM_BindStateDelaySuicide_C;

}

