#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SM_ConditionCheckInstState

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "SMSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SM_ConditionCheckInstState.BP_SM_ConditionCheckInstState_C
// 0x0010 (0x0048 - 0x0038)
class UBP_SM_ConditionCheckInstState_C final : public UASMConditionBase
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0038(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SM_ConditionCheckInstState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SM_ConditionCheckInstState_C")
	}
	static class UBP_SM_ConditionCheckInstState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SM_ConditionCheckInstState_C>();
	}
};
DUMPER7_ASSERTS_UBP_SM_ConditionCheckInstState_C;

}

