#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StreamingSourceActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StreamingSourceActor.BP_StreamingSourceActor_C
// 0x0010 (0x02C0 - 0x02B0)
class ABP_StreamingSourceActor_C final : public AActor
{
public:
	class UWorldPartitionStreamingSourceComponent* WorldPartitionStreamingSource;                    // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StreamingSourceActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StreamingSourceActor_C")
	}
	static class ABP_StreamingSourceActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StreamingSourceActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_StreamingSourceActor_C;

}

