#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SM_ConditionBuffStack

#include "Basic.hpp"

#include "SMSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SM_ConditionBuffStack.BP_SM_ConditionBuffStack_C
// 0x0010 (0x0048 - 0x0038)
class UBP_SM_ConditionBuffStack_C final : public UASMConditionBase
{
public:
	int64                                         BuffId;                                            // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Min;                                               // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max;                                               // 0x0044(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SM_ConditionBuffStack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SM_ConditionBuffStack_C")
	}
	static class UBP_SM_ConditionBuffStack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SM_ConditionBuffStack_C>();
	}
};
DUMPER7_ASSERTS_UBP_SM_ConditionBuffStack_C;

}

