#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SM_ConditionAttribute

#include "Basic.hpp"

#include "EAttributeType_structs.hpp"
#include "SMSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SM_ConditionAttribute.BP_SM_ConditionAttribute_C
// 0x0010 (0x0048 - 0x0038)
class UBP_SM_ConditionAttribute_C final : public UASMConditionBase
{
public:
	EAttributeType                                属性类型;                                          // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Min;                                               // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max;                                               // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SM_ConditionAttribute_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SM_ConditionAttribute_C")
	}
	static class UBP_SM_ConditionAttribute_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SM_ConditionAttribute_C>();
	}
};
DUMPER7_ASSERTS_UBP_SM_ConditionAttribute_C;

}

