#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UiSceneRenderingComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_UiSceneRenderingComponent.BP_UiSceneRenderingComponent_C.OnKuroStartUiScene
// 0x0030 (0x0030 - 0x0000)
struct BP_UiSceneRenderingComponent_C_OnKuroStartUiScene final
{
public:
	class FString                                 UiScenePath;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_UiSceneRenderingComponent_C_OnKuroStartUiScene;

// Function BP_UiSceneRenderingComponent.BP_UiSceneRenderingComponent_C.Init
// 0x0008 (0x0008 - 0x0000)
struct BP_UiSceneRenderingComponent_C_Init final
{
public:
	class ABP_GlobalGI_C*                         InGlobalGI;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_UiSceneRenderingComponent_C_Init;

// Function BP_UiSceneRenderingComponent.BP_UiSceneRenderingComponent_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct BP_UiSceneRenderingComponent_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_UiSceneRenderingComponent_C_ReceiveEndPlay;

// Function BP_UiSceneRenderingComponent.BP_UiSceneRenderingComponent_C.ExecuteUbergraph_BP_UiSceneRenderingComponent
// 0x0008 (0x0008 - 0x0000)
struct BP_UiSceneRenderingComponent_C_ExecuteUbergraph_BP_UiSceneRenderingComponent final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_UiSceneRenderingComponent_C_ExecuteUbergraph_BP_UiSceneRenderingComponent;

}

