#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EBatchBulletPosition

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EBatchBulletPosition.EBatchBulletPosition
// NumValues: 0x0004
enum class EBatchBulletPosition : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator3                           = 2,
	EBatchBulletPosition_MAX                 = 3,
};

}

