#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GmDebugBlueprintFunctionLibrary

#include "Basic.hpp"


namespace SDK::Params
{

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsRunGm
// 0x0018 (0x0018 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsRunGm final
{
public:
	class FString                                 gmStr;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsRunGm;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGetGmIsOpen
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGetGmIsOpen final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGetGmIsOpen;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmGetEntityActorByChildActor
// 0x0018 (0x0018 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmGetEntityActorByChildActor final
{
public:
	class AActor*                                 childActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmGetEntityActorByChildActor;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmGetEntityPbDataIdByChildActor
// 0x0018 (0x0018 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmGetEntityPbDataIdByChildActor final
{
public:
	class AActor*                                 childActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmGetEntityPbDataIdByChildActor;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmShowEntityViewByPbDataId
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmShowEntityViewByPbDataId final
{
public:
	int32                                         pbDataId;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmShowEntityViewByPbDataId;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmGetIsGameCommandServiceRunning
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmGetIsGameCommandServiceRunning final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmGetIsGameCommandServiceRunning;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.OpenWbpDebugWin
// 0x0008 (0x0008 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_OpenWbpDebugWin final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_OpenWbpDebugWin;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmStartGameCommandService
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmStartGameCommandService final
{
public:
	int32                                         port;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmStartGameCommandService;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmStopGameCommandService
// 0x0008 (0x0008 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmStopGameCommandService final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmStopGameCommandService;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsCheatInputRequest
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsCheatInputRequest final
{
public:
	int32                                         type;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsCheatInputRequest;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGetAoeDestroyEnemyActivated
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGetAoeDestroyEnemyActivated final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGetAoeDestroyEnemyActivated;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsSetAoeDestroyEnemyActivated
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsSetAoeDestroyEnemyActivated final
{
public:
	bool                                          aoeDestroyEnemyActivated;                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsSetAoeDestroyEnemyActivated;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGetAoeDestroyEnemyRange
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGetAoeDestroyEnemyRange final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGetAoeDestroyEnemyRange;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsSetAoeDestroyEnemyRange
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsSetAoeDestroyEnemyRange final
{
public:
	float                                         aoeDestroyEnemyRange;                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsSetAoeDestroyEnemyRange;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsGmLoadFightDt
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsGmLoadFightDt final
{
public:
	int32                                         entityId;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsGmLoadFightDt;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.TsTestLifePoint
// 0x0020 (0x0020 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_TsTestLifePoint final
{
public:
	float                                         p11;                                               // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         p2;                                                // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         p3;                                                // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         p4;                                                // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         p5;                                                // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         p6;                                                // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                __WorldContext;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_TsTestLifePoint;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.InitLevelRangeDebugData
// 0x0008 (0x0008 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_InitLevelRangeDebugData final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_InitLevelRangeDebugData;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.GetLevelRangeDebugData
// 0x0020 (0x0020 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_GetLevelRangeDebugData final
{
public:
	int32                                         type;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          enable;                                            // 0x0004(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         r;                                                 // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         g;                                                 // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         b;                                                 // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_GetLevelRangeDebugData;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.SetLevelRangeDebugMode
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_SetLevelRangeDebugMode final
{
public:
	int32                                         mode;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_SetLevelRangeDebugMode;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.SetLevelRangeDebugData
// 0x0020 (0x0020 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_SetLevelRangeDebugData final
{
public:
	int32                                         type;                                              // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          enable;                                            // 0x0004(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         r;                                                 // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         g;                                                 // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         b;                                                 // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                __WorldContext;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_SetLevelRangeDebugData;

// Function GmDebugBlueprintFunctionLibrary.GmDebugBlueprintFunctionLibrary_C.GetLevelRangeDebugMode
// 0x0010 (0x0010 - 0x0000)
struct GmDebugBlueprintFunctionLibrary_C_GetLevelRangeDebugMode final
{
public:
	class UObject*                                __WorldContext;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GmDebugBlueprintFunctionLibrary_C_GetLevelRangeDebugMode;

}

