#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroNetwork

#include "Basic.hpp"

#include "KuroNetwork_structs.hpp"
#include "JsEnv_structs.hpp"


namespace SDK::Params
{

// Function KuroNetwork.KuroHttp.Get
// 0x0090 (0x0090 - 0x0000)
struct KuroHttp_Get final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            HeaderParam;                                       // 0x0010(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TDelegate<void(bool bConnectedSuccessfully, int32 HttpResponseCode, const class FString& Data)> Handle; // 0x0060(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0088(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_Get;

// Function KuroNetwork.KuroHttp.GetDefaultHeader
// 0x0050 (0x0050 - 0x0000)
struct KuroHttp_GetDefaultHeader final
{
public:
	TMap<class FString, class FString>            ReturnValue;                                       // 0x0000(0x0050)(Parm, OutParm, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroHttp_GetDefaultHeader;

// Function KuroNetwork.KuroHttp.Post
// 0x00A0 (0x00A0 - 0x0000)
struct KuroHttp_Post final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            HeaderParam;                                       // 0x0010(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	class FString                                 Content;                                           // 0x0060(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(bool bConnectedSuccessfully, int32 HttpResponseCode, const class FString& Data)> Handle; // 0x0070(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0098(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_Post;

// Function KuroNetwork.KuroHttp.PostAli
// 0x0080 (0x0080 - 0x0000)
struct KuroHttp_PostAli final
{
public:
	TMap<class FString, class FString>            QueryParameter;                                    // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TDelegate<void(bool bConnectedSuccessfully, int32 HttpResponseCode, const class FString& Data)> Handle; // 0x0050(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0078(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_PostAli;

// Function KuroNetwork.KuroHttp.PostRpt
// 0x0048 (0x0048 - 0x0000)
struct KuroHttp_PostRpt final
{
public:
	class FString                                 ContentStr;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsGlobal;                                          // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& Data, int32 LocalErrorCode, int32 RemoteErrorCode, int32 HttpResponseCode, bool bConnectedSuccessfully)> Handle; // 0x0018(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0040(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_PostRpt;

// Function KuroNetwork.KuroHttp.PostRpt1
// 0x0058 (0x0058 - 0x0000)
struct KuroHttp_PostRpt1 final
{
public:
	class FString                                 ContentStr;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Content1Str;                                       // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsGlobal;                                          // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& Data, int32 LocalErrorCode, int32 RemoteErrorCode, int32 HttpResponseCode, bool bConnectedSuccessfully)> Handle; // 0x0028(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0050(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_PostRpt1;

// Function KuroNetwork.KuroHttp.PostRpt2
// 0x0060 (0x0060 - 0x0000)
struct KuroHttp_PostRpt2 final
{
public:
	class FString                                 Url;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ContentStr;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Content1Str;                                       // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(const class FString& Data, int32 LocalErrorCode, int32 RemoteErrorCode, int32 HttpResponseCode, bool bConnectedSuccessfully)> Handle; // 0x0030(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	float                                         InTimeoutSecs;                                     // 0x0058(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttp_PostRpt2;

// Function KuroNetwork.KuroHttpServerRequestProxy.GetHeader
// 0x0028 (0x0028 - 0x0000)
struct KuroHttpServerRequestProxy_GetHeader final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         OutHeader;                                         // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttpServerRequestProxy_GetHeader;

// Function KuroNetwork.KuroHttpServerRequestProxy.GetRequest
// 0x0010 (0x0010 - 0x0000)
struct KuroHttpServerRequestProxy_GetRequest final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroHttpServerRequestProxy_GetRequest;

// Function KuroNetwork.KuroHttpServerRequestProxy.Response
// 0x0018 (0x0018 - 0x0000)
struct KuroHttpServerRequestProxy_Response final
{
public:
	class FString                                 Json;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSuccess;                                          // 0x0010(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroHttpServerRequestProxy_Response;

// Function KuroNetwork.KuroHttpServerRouterProxy.BindRoute
// 0x0010 (0x0010 - 0x0000)
struct KuroHttpServerRouterProxy_BindRoute final
{
public:
	class FString                                 ModuleName;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroHttpServerRouterProxy_BindRoute;

// Function KuroNetwork.KuroHttpServerRouterProxy.CreateRouter
// 0x0004 (0x0004 - 0x0000)
struct KuroHttpServerRouterProxy_CreateRouter final
{
public:
	int32                                         Port;                                              // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroHttpServerRouterProxy_CreateRouter;

// Function KuroNetwork.KuroKcpClient.Connect
// 0x0018 (0x0018 - 0x0000)
struct KuroKcpClient_Connect final
{
public:
	class FString                                 Addr;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Port;                                              // 0x0010(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CrcCheckDisable;                                   // 0x0014(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0015(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroKcpClient_Connect;

// Function KuroNetwork.KuroKcpClient.GetDebugString
// 0x0038 (0x0038 - 0x0000)
struct KuroKcpClient_GetDebugString final
{
public:
	struct FArrayBuffer                           ArrayBuffer;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	class FString                                 Separator;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         MsgId;                                             // 0x0020(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SeqNo;                                             // 0x0024(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_GetDebugString;

// Function KuroNetwork.KuroKcpClient.HandleKcpConnect
// 0x0008 (0x0008 - 0x0000)
struct KuroKcpClient_HandleKcpConnect final
{
public:
	uint32                                        NeedCrcCheck;                                      // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint32                                        Conv;                                              // 0x0004(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_HandleKcpConnect;

// Function KuroNetwork.KuroKcpClient.SendM
// 0x0028 (0x0028 - 0x0000)
struct KuroKcpClient_SendM final
{
public:
	int8                                          MsgType;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SeqNo;                                             // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         RpcId;                                             // 0x0008(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         MsgId;                                             // 0x000A(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FArrayBuffer                           ArrayBuffer;                                       // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          UseKcp;                                            // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0021(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroKcpClient_SendM;

// Function KuroNetwork.KuroKcpClient.SendTcpMessage
// 0x0018 (0x0018 - 0x0000)
struct KuroKcpClient_SendTcpMessage final
{
public:
	int16                                         RpcId;                                             // 0x0000(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         MsgId;                                             // 0x0002(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FArrayBuffer                           ArrayBuffer;                                       // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SendTcpMessage;

// Function KuroNetwork.KuroKcpClient.SetEnType
// 0x0004 (0x0004 - 0x0000)
struct KuroKcpClient_SetEnType final
{
public:
	uint8                                         Type;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x1];                                        // 0x0001(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int16                                         MsgId;                                             // 0x0002(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetEnType;

// Function KuroNetwork.KuroKcpClient.SetK
// 0x0020 (0x0020 - 0x0000)
struct KuroKcpClient_SetK final
{
public:
	uint8                                         Type;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FArrayBuffer                           KeyBuffer;                                         // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroKcpClient_SetK;

// Function KuroNetwork.KuroKcpClient.SetKcpMtu
// 0x0004 (0x0004 - 0x0000)
struct KuroKcpClient_SetKcpMtu final
{
public:
	int32                                         Mtu;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetKcpMtu;

// Function KuroNetwork.KuroKcpClient.SetKcpNoDelay
// 0x0010 (0x0010 - 0x0000)
struct KuroKcpClient_SetKcpNoDelay final
{
public:
	int32                                         NoDelay;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Interval;                                          // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Resend;                                            // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Nc;                                                // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetKcpNoDelay;

// Function KuroNetwork.KuroKcpClient.SetKcpSegmentSize
// 0x0004 (0x0004 - 0x0000)
struct KuroKcpClient_SetKcpSegmentSize final
{
public:
	int32                                         SegmentSize;                                       // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetKcpSegmentSize;

// Function KuroNetwork.KuroKcpClient.SetKcpStream
// 0x0001 (0x0001 - 0x0000)
struct KuroKcpClient_SetKcpStream final
{
public:
	bool                                          bStream;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetKcpStream;

// Function KuroNetwork.KuroKcpClient.SetKcpWndSize
// 0x0008 (0x0008 - 0x0000)
struct KuroKcpClient_SetKcpWndSize final
{
public:
	int32                                         SndWnd;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         RcvWnd;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_SetKcpWndSize;

// Function KuroNetwork.KuroKcpClient.StartTcpConnect
// 0x0004 (0x0004 - 0x0000)
struct KuroKcpClient_StartTcpConnect final
{
public:
	int32                                         Port;                                              // 0x0000(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_StartTcpConnect;

// Function KuroNetwork.KuroKcpClient.TickOutside
// 0x0004 (0x0004 - 0x0000)
struct KuroKcpClient_TickOutside final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_TickOutside;

// Function KuroNetwork.KuroKcpClient.IsTcpConnectStart
// 0x0001 (0x0001 - 0x0000)
struct KuroKcpClient_IsTcpConnectStart final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpClient_IsTcpConnectStart;

// Function KuroNetwork.KuroKcpTestWorker.OnRecvException
// 0x0020 (0x0020 - 0x0000)
struct KuroKcpTestWorker_OnRecvException final
{
public:
	int32                                         SeqNo;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         RpcId;                                             // 0x0004(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ErrorCode;                                         // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FArrayBuffer                           MessageBuff;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpTestWorker_OnRecvException;

// Function KuroNetwork.KuroKcpTestWorker.OnRecvPush
// 0x0018 (0x0018 - 0x0000)
struct KuroKcpTestWorker_OnRecvPush final
{
public:
	int32                                         SeqNo;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        MessageId;                                         // 0x0004(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FArrayBuffer                           MessageBuff;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpTestWorker_OnRecvPush;

// Function KuroNetwork.KuroKcpTestWorker.OnRecvResponse
// 0x0018 (0x0018 - 0x0000)
struct KuroKcpTestWorker_OnRecvResponse final
{
public:
	int32                                         SeqNo;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int16                                         RpcId;                                             // 0x0004(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint16                                        MessageId;                                         // 0x0006(0x0002)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FArrayBuffer                           MessageBuff;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroKcpTestWorker_OnRecvResponse;

// Function KuroNetwork.KuroNetworkChange.GetNetworkType
// 0x0001 (0x0001 - 0x0000)
struct KuroNetworkChange_GetNetworkType final
{
public:
	uint8                                         ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkChange_GetNetworkType;

// Function KuroNetwork.KuroNetworkDetection.DetectionFinish
// 0x0001 (0x0001 - 0x0000)
struct KuroNetworkDetection_DetectionFinish final
{
public:
	bool                                          bSuccess;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_DetectionFinish;

// Function KuroNetwork.KuroNetworkDetection.GetCurrentProxyAddress
// 0x0010 (0x0010 - 0x0000)
struct KuroNetworkDetection_GetCurrentProxyAddress final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_GetCurrentProxyAddress;

// Function KuroNetwork.KuroNetworkDetection.GetDetectionConfig
// 0x0020 (0x0020 - 0x0000)
struct KuroNetworkDetection_GetDetectionConfig final
{
public:
	class FString                                 ServerName;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_GetDetectionConfig;

// Function KuroNetwork.KuroNetworkDetection.ResolveDomainName
// 0x0038 (0x0038 - 0x0000)
struct KuroNetworkDetection_ResolveDomainName final
{
public:
	class FString                                 DomainName;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 ErrorCode)>              Callback;                                          // 0x0010(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_ResolveDomainName;

// Function KuroNetwork.KuroNetworkDetection.SetCDNConfig
// 0x0010 (0x0010 - 0x0000)
struct KuroNetworkDetection_SetCDNConfig final
{
public:
	class FString                                 CDNConfig;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_SetCDNConfig;

// Function KuroNetwork.KuroNetworkDetection.TestUdpReachable
// 0x0048 (0x0048 - 0x0000)
struct KuroNetworkDetection_TestUdpReachable final
{
public:
	class FString                                 IpAddress;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<int32>                                 Ports;                                             // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	TDelegate<void(int32 SuccessCount, int32 ErrorCode)> ResultDelegate;                             // 0x0020(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroNetworkDetection_TestUdpReachable;

// Function KuroNetwork.KuroTcpClient.Connect
// 0x0018 (0x0018 - 0x0000)
struct KuroTcpClient_Connect final
{
public:
	class FString                                 Addr;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Port;                                              // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroTcpClient_Connect;

// Function KuroNetwork.KuroTcpClient.Send
// 0x0010 (0x0010 - 0x0000)
struct KuroTcpClient_Send final
{
public:
	TArray<uint8>                                 Data;                                              // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroTcpClient_Send;

// Function KuroNetwork.KuroTcpClient.TickOutside
// 0x0004 (0x0004 - 0x0000)
struct KuroTcpClient_TickOutside final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroTcpClient_TickOutside;

// Function KuroNetwork.SendHttpRequest.HttpRequest
// 0x0030 (0x0030 - 0x0000)
struct SendHttpRequest_HttpRequest final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHttpMethod                                   Method;                                            // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PostBody;                                          // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USendHttpRequest*                       ReturnValue;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SendHttpRequest_HttpRequest;

// Function KuroNetwork.SendHttpRequest.HttpRequestEx
// 0x0040 (0x0040 - 0x0000)
struct SendHttpRequest_HttpRequestEx final
{
public:
	class FString                                 URL;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHttpMethod                                   Method;                                            // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 PostBody;                                          // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 HeaderParam;                                       // 0x0028(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USendHttpRequest*                       ReturnValue;                                       // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SendHttpRequest_HttpRequestEx;

}

