#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroComputeShader

#include "Basic.hpp"

#include "KuroComputeShader_classes.hpp"


namespace SDK
{

// Function KuroComputeShader.KuroCS_Cloth_DynamicPin.InitShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_DynamicPin::InitShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_DynamicPin", "InitShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_DynamicPin.ReleaseShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_DynamicPin::ReleaseShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_DynamicPin", "ReleaseShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_DynamicPin.StartSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_DynamicPin::StartSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_DynamicPin", "StartSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_DynamicPin.StopSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_DynamicPin::StopSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_DynamicPin", "StopSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_Path.InitShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_Path::InitShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_Path", "InitShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_Path.ReleaseShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_Path::ReleaseShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_Path", "ReleaseShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_Path.StartSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_Path::StartSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_Path", "StartSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCS_Cloth_Path.StopSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCS_Cloth_Path::StopSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCS_Cloth_Path", "StopSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSCloth.InitShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCSCloth::InitShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSCloth", "InitShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSCloth.ReleaseShaderManager
// (Final, Native, Public, BlueprintCallable)

void AKuroCSCloth::ReleaseShaderManager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSCloth", "ReleaseShaderManager");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSCloth.StartSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCSCloth::StartSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSCloth", "StartSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSCloth.StopSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCSCloth::StopSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSCloth", "StopSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSDoubleChain.StartSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCSDoubleChain::StartSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSDoubleChain", "StartSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSDoubleChain.StopSimulation
// (Final, Native, Public, BlueprintCallable)

void AKuroCSDoubleChain::StopSimulation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSDoubleChain", "StopSimulation");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSSkeltalPlant.afterBeginPlay
// (Final, Native, Public, BlueprintCallable)

void AKuroCSSkeltalPlant::afterBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSSkeltalPlant", "afterBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSSkeltalPlant.BeginRenderShader
// (Final, Native, Public, BlueprintCallable)

void AKuroCSSkeltalPlant::BeginRenderShader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSSkeltalPlant", "BeginRenderShader");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSSkeltalPlant.BuildParticleData
// (Final, Native, Public, BlueprintCallable)

void AKuroCSSkeltalPlant::BuildParticleData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSSkeltalPlant", "BuildParticleData");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroComputeShader.KuroCSSkeltalPlant.EndRenderShader
// (Final, Native, Public, BlueprintCallable)

void AKuroCSSkeltalPlant::EndRenderShader()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroCSSkeltalPlant", "EndRenderShader");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

