#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroHotPatch

#include "Basic.hpp"


namespace SDK::Params
{

// Function KuroHotPatch.DownloaderProxy.GetContentLength
// 0x0008 (0x0008 - 0x0000)
struct DownloaderProxy_GetContentLength final
{
public:
	int64                                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_GetContentLength;

// Function KuroHotPatch.DownloaderProxy.GetReceivedSize
// 0x0008 (0x0008 - 0x0000)
struct DownloaderProxy_GetReceivedSize final
{
public:
	int64                                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_GetReceivedSize;

// Function KuroHotPatch.DownloaderProxy.GetSavedSize
// 0x0008 (0x0008 - 0x0000)
struct DownloaderProxy_GetSavedSize final
{
public:
	int64                                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_GetSavedSize;

// Function KuroHotPatch.DownloaderProxy.GetTotalDownloadTime
// 0x0004 (0x0004 - 0x0000)
struct DownloaderProxy_GetTotalDownloadTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_GetTotalDownloadTime;

// Function KuroHotPatch.DownloaderProxy.HasComplete
// 0x0001 (0x0001 - 0x0000)
struct DownloaderProxy_HasComplete final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_HasComplete;

// Function KuroHotPatch.DownloaderProxy.SetCompleteCallback
// 0x0028 (0x0028 - 0x0000)
struct DownloaderProxy_SetCompleteCallback final
{
public:
	TDelegate<void(uint8 DownloadState, int32 HttpState)> InCb;                                      // 0x0000(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_SetCompleteCallback;

// Function KuroHotPatch.DownloaderProxy.SetProgressCallback
// 0x0028 (0x0028 - 0x0000)
struct DownloaderProxy_SetProgressCallback final
{
public:
	TDelegate<void(int64 ThisTimeReceiveSize, int64 ReceivedSize, int64 SavedSize)> InCb;            // 0x0000(0x0028)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_DownloaderProxy_SetProgressCallback;

// Function KuroHotPatch.DownloaderProxy.Start
// 0x0058 (0x0058 - 0x0000)
struct DownloaderProxy_Start final
{
public:
	class FString                                 Url;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SavePath;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Suffix;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         InFileSize;                                        // 0x0030(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InLimitTime;                                       // 0x0038(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceNew;                                         // 0x003C(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          InCache;                                           // 0x003D(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3E[0x2];                                       // 0x003E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Sha1;                                              // 0x0040(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InTimeout;                                         // 0x0050(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNewTick;                                          // 0x0054(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_DownloaderProxy_Start;

// Function KuroHotPatch.KuroConfigPatcher.UpdateConfigs
// 0x0010 (0x0010 - 0x0000)
struct KuroConfigPatcher_UpdateConfigs final
{
public:
	class FString                                 ConfigListPath;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroConfigPatcher_UpdateConfigs;

// Function KuroHotPatch.KuroBinPatch.BeginPatch
// 0x0030 (0x0030 - 0x0000)
struct KuroBinPatch_BeginPatch final
{
public:
	class FString                                 Diff;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OldDir;                                            // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 NewDir;                                            // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroBinPatch_BeginPatch;

// Function KuroHotPatch.KuroLauncherLibrary.CheckFileSha1
// 0x0028 (0x0028 - 0x0000)
struct KuroLauncherLibrary_CheckFileSha1 final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CheckSha1Hash;                                     // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_CheckFileSha1;

// Function KuroHotPatch.KuroLauncherLibrary.CopyFile
// 0x0028 (0x0028 - 0x0000)
struct KuroLauncherLibrary_CopyFile final
{
public:
	class FString                                 DstPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SrcPath;                                           // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_CopyFile;

// Function KuroHotPatch.KuroLauncherLibrary.Decrypt
// 0x0028 (0x0028 - 0x0000)
struct KuroLauncherLibrary_Decrypt final
{
public:
	class FString                                 InCipher;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutPlain;                                          // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_Decrypt;

// Function KuroHotPatch.KuroLauncherLibrary.DeleteDirectory
// 0x0018 (0x0018 - 0x0000)
struct KuroLauncherLibrary_DeleteDirectory final
{
public:
	class FString                                 DirPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_DeleteDirectory;

// Function KuroHotPatch.KuroLauncherLibrary.DeleteFile
// 0x0018 (0x0018 - 0x0000)
struct KuroLauncherLibrary_DeleteFile final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_DeleteFile;

// Function KuroHotPatch.KuroLauncherLibrary.DoesDiskHaveEnoughSpace
// 0x0020 (0x0020 - 0x0000)
struct KuroLauncherLibrary_DoesDiskHaveEnoughSpace final
{
public:
	class FString                                 CheckPath;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         CheckSize;                                         // 0x0010(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_DoesDiskHaveEnoughSpace;

// Function KuroHotPatch.KuroLauncherLibrary.Encrypt
// 0x0028 (0x0028 - 0x0000)
struct KuroLauncherLibrary_Encrypt final
{
public:
	class FString                                 InPlain;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutCipher;                                         // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_Encrypt;

// Function KuroHotPatch.KuroLauncherLibrary.GameSavedDir
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GameSavedDir final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GameSavedDir;

// Function KuroHotPatch.KuroLauncherLibrary.GetAppChangeList
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GetAppChangeList final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetAppChangeList;

// Function KuroHotPatch.KuroLauncherLibrary.GetAppInternalUseType
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GetAppInternalUseType final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetAppInternalUseType;

// Function KuroHotPatch.KuroLauncherLibrary.GetAppParallel
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GetAppParallel final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetAppParallel;

// Function KuroHotPatch.KuroLauncherLibrary.GetAppReleaseType
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GetAppReleaseType final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetAppReleaseType;

// Function KuroHotPatch.KuroLauncherLibrary.GetAppVersion
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_GetAppVersion final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetAppVersion;

// Function KuroHotPatch.KuroLauncherLibrary.GetConfig
// 0x0038 (0x0038 - 0x0000)
struct KuroLauncherLibrary_GetConfig final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DefaultValue;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutStr;                                            // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetConfig;

// Function KuroHotPatch.KuroLauncherLibrary.GetFileSize
// 0x0018 (0x0018 - 0x0000)
struct KuroLauncherLibrary_GetFileSize final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetFileSize;

// Function KuroHotPatch.KuroLauncherLibrary.GetGConfigString
// 0x0038 (0x0038 - 0x0000)
struct KuroLauncherLibrary_GetGConfigString final
{
public:
	class FString                                 Section;                                           // 0x0000(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Key;                                               // 0x0010(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutStr;                                            // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetGConfigString;

// Function KuroHotPatch.KuroLauncherLibrary.GetNetworkConnectionType
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_GetNetworkConnectionType final
{
public:
	uint8                                         ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetNetworkConnectionType;

// Function KuroHotPatch.KuroLauncherLibrary.GetRemainPrecompileShaders
// 0x0004 (0x0004 - 0x0000)
struct KuroLauncherLibrary_GetRemainPrecompileShaders final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetRemainPrecompileShaders;

// Function KuroHotPatch.KuroLauncherLibrary.GetTotalAndFreeSpace
// 0x0020 (0x0020 - 0x0000)
struct KuroLauncherLibrary_GetTotalAndFreeSpace final
{
public:
	class FString                                 CheckPath;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         FreeSize;                                          // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetTotalAndFreeSpace;

// Function KuroHotPatch.KuroLauncherLibrary.GetTotalPrecompileShaders
// 0x0004 (0x0004 - 0x0000)
struct KuroLauncherLibrary_GetTotalPrecompileShaders final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_GetTotalPrecompileShaders;

// Function KuroHotPatch.KuroLauncherLibrary.IsFirstIntoLauncher
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_IsFirstIntoLauncher final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_IsFirstIntoLauncher;

// Function KuroHotPatch.KuroLauncherLibrary.IsLocalPackaging
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_IsLocalPackaging final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_IsLocalPackaging;

// Function KuroHotPatch.KuroLauncherLibrary.IsSeparateVideo
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_IsSeparateVideo final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_IsSeparateVideo;

// Function KuroHotPatch.KuroLauncherLibrary.IsStartupMountSuccess
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_IsStartupMountSuccess final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_IsStartupMountSuccess;

// Function KuroHotPatch.KuroLauncherLibrary.MakeDirectory
// 0x0018 (0x0018 - 0x0000)
struct KuroLauncherLibrary_MakeDirectory final
{
public:
	class FString                                 DirPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_MakeDirectory;

// Function KuroHotPatch.KuroLauncherLibrary.MoveFile
// 0x0028 (0x0028 - 0x0000)
struct KuroLauncherLibrary_MoveFile final
{
public:
	class FString                                 DstPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SrcPath;                                           // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroLauncherLibrary_MoveFile;

// Function KuroHotPatch.KuroLauncherLibrary.NeedClearPatchPaks
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_NeedClearPatchPaks final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_NeedClearPatchPaks;

// Function KuroHotPatch.KuroLauncherLibrary.NeedHotPatch
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_NeedHotPatch final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_NeedHotPatch;

// Function KuroHotPatch.KuroLauncherLibrary.NeedRestartApp
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_NeedRestartApp final
{
public:
	uint8                                         ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_NeedRestartApp;

// Function KuroHotPatch.KuroLauncherLibrary.RestartApplication
// 0x0010 (0x0010 - 0x0000)
struct KuroLauncherLibrary_RestartApplication final
{
public:
	class FString                                 ScriptContent;                                     // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_RestartApplication;

// Function KuroHotPatch.KuroLauncherLibrary.SetPrecompileShaderBatchMode
// 0x0004 (0x0004 - 0x0000)
struct KuroLauncherLibrary_SetPrecompileShaderBatchMode final
{
public:
	int32                                         Mode;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_SetPrecompileShaderBatchMode;

// Function KuroHotPatch.KuroLauncherLibrary.SetRestartApp
// 0x0001 (0x0001 - 0x0000)
struct KuroLauncherLibrary_SetRestartApp final
{
public:
	uint8                                         RestartType;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroLauncherLibrary_SetRestartApp;

// Function KuroHotPatch.KuroPakMountStatic.AddSha1Check
// 0x0020 (0x0020 - 0x0000)
struct KuroPakMountStatic_AddSha1Check final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CheckSha1Hash;                                     // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_AddSha1Check;

// Function KuroHotPatch.KuroPakMountStatic.GetSha1CheckFailedCount
// 0x0004 (0x0004 - 0x0000)
struct KuroPakMountStatic_GetSha1CheckFailedCount final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_GetSha1CheckFailedCount;

// Function KuroHotPatch.KuroPakMountStatic.IsSha1CheckWorking
// 0x0001 (0x0001 - 0x0000)
struct KuroPakMountStatic_IsSha1CheckWorking final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_IsSha1CheckWorking;

// Function KuroHotPatch.KuroPakMountStatic.MakePakDirPatch
// 0x0038 (0x0038 - 0x0000)
struct KuroPakMountStatic_MakePakDirPatch final
{
public:
	class FString                                 OldPakPath;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DiffPath;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 NewPatchPath;                                      // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroPakMountStatic_MakePakDirPatch;

// Function KuroHotPatch.KuroPakMountStatic.MakePakPatch
// 0x0038 (0x0038 - 0x0000)
struct KuroPakMountStatic_MakePakPatch final
{
public:
	class FString                                 OldPakPath;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DiffPath;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 NewPatchPath;                                      // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0030(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroPakMountStatic_MakePakPatch;

// Function KuroHotPatch.KuroPakMountStatic.MountFromManifest
// 0x0010 (0x0010 - 0x0000)
struct KuroPakMountStatic_MountFromManifest final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_MountFromManifest;

// Function KuroHotPatch.KuroPakMountStatic.MountPak
// 0x0018 (0x0018 - 0x0000)
struct KuroPakMountStatic_MountPak final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Order;                                             // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_KuroPakMountStatic_MountPak;

// Function KuroHotPatch.KuroPakMountStatic.RemoveSha1Check
// 0x0010 (0x0010 - 0x0000)
struct KuroPakMountStatic_RemoveSha1Check final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_RemoveSha1Check;

// Function KuroHotPatch.KuroPakMountStatic.Save
// 0x0010 (0x0010 - 0x0000)
struct KuroPakMountStatic_Save final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_Save;

// Function KuroHotPatch.KuroPakMountStatic.UnmountFromManifest
// 0x0010 (0x0010 - 0x0000)
struct KuroPakMountStatic_UnmountFromManifest final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_UnmountFromManifest;

// Function KuroHotPatch.KuroPakMountStatic.UnmountPak
// 0x0010 (0x0010 - 0x0000)
struct KuroPakMountStatic_UnmountPak final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_KuroPakMountStatic_UnmountPak;

}

