#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroSplines

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class KuroSplines.KuroMoveSplineComponent
// 0x0050 (0x0660 - 0x0610)
class UKuroMoveSplineComponent final : public USplineComponent
{
public:
	TArray<int32>                                 MoveStates;                                        // 0x0608(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 MoveSpeeds;                                        // 0x0618(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 IgnorePoints;                                      // 0x0628(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 StayTimes;                                         // 0x0638(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 IsHides;                                           // 0x0648(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_658[0x8];                                      // 0x0658(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	int32 GetIgnorePoint(int32 Index_0);
	int32 GetIsHide(int32 Index_0);
	int32 GetMoveSpeed(int32 Index_0);
	int32 GetMoveState(int32 Index_0);
	int32 GetStayTime(int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroMoveSplineComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroMoveSplineComponent")
	}
	static class UKuroMoveSplineComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroMoveSplineComponent>();
	}
};
DUMPER7_ASSERTS_UKuroMoveSplineComponent;

// Class KuroSplines.KuroParkourSplineComponent
// 0x0030 (0x0640 - 0x0610)
class UKuroParkourSplineComponent final : public USplineComponent
{
public:
	TArray<float>                                 RadiusGroup;                                       // 0x0608(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<float>                                 ModifiedTimes;                                     // 0x0618(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<int32>                                 BuffIds;                                           // 0x0628(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_638[0x8];                                      // 0x0638(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	int32 GetBuffId(int32 Index_0);
	float GetModifiedTime(int32 Index_0);
	float GetRadius(int32 Index_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroParkourSplineComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroParkourSplineComponent")
	}
	static class UKuroParkourSplineComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroParkourSplineComponent>();
	}
};
DUMPER7_ASSERTS_UKuroParkourSplineComponent;

}

