#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroSqliteBpLib

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class KuroSqliteBpLib.KuroPrepareStatementLib
// 0x0000 (0x0030 - 0x0030)
class UKuroPrepareStatementLib final : public UBlueprintFunctionLibrary
{
public:
	static bool ClearBindings(const int32 InId);
	static void CloseAllConnection();
	static void CloseConnection(const int32 InId);
	static int32 CreateStatement(const class FName& InDbPath, const class FString& InCommand);
	static void DestroyStatement(const int32 InId);
	static bool GetColumnValueBytes(const int32 InId, const int32 InColumnIndex, struct FArrayBuffer* OutValue);
	static int32 GetOrCreateStatement(const class FName& InDbPath, const class FString& InCommand);
	static bool Reset(const int32 InId);
	static bool SetBindingValueBigInt(const int32 InId, const int32 InBindingIndex, const int64 InValue);
	static bool SetBindingValueBool(const int32 InId, const int32 InBindingIndex, const bool InValue);
	static bool SetBindingValueFloat(const int32 InId, const int32 InBindingIndex, const float InValue);
	static bool SetBindingValueFloat64(const int32 InId, const int32 InBindingIndex, const double InValue);
	static bool SetBindingValueInt(const int32 InId, const int32 InBindingIndex, const int32 InValue);
	static bool SetBindingValueString(const int32 InId, const int32 InBindingIndex, const class FString& InValue);
	static int32 Step(const int32 InId);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroPrepareStatementLib")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroPrepareStatementLib")
	}
	static class UKuroPrepareStatementLib* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroPrepareStatementLib>();
	}
};
DUMPER7_ASSERTS_UKuroPrepareStatementLib;

// Class KuroSqliteBpLib.KuroQueryStatLibrary
// 0x0000 (0x0030 - 0x0030)
class UKuroQueryStatLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void AppendString(const class FString& Content);
	static void CloseTestDataFile();
	static void InvokeCloseSaveQueryArgsFileAction();
	static void InvokeTestSqliteAction();
	static void SetCloseSaveQueryArgsFileAction(const struct FJsObject& Action);
	static void SetTestDataSavePath(const class FString& Path);
	static void SetTestSqliteAction(const struct FJsObject& Action);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroQueryStatLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroQueryStatLibrary")
	}
	static class UKuroQueryStatLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroQueryStatLibrary>();
	}
};
DUMPER7_ASSERTS_UKuroQueryStatLibrary;

// Class KuroSqliteBpLib.KuroSqliteLibrary
// 0x0000 (0x0030 - 0x0030)
class UKuroSqliteLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void CloseAllConnections();
	static bool Execute(const class FString& DbPath, const class FString& Sql);
	static void ExecuteAsync(const class FString& DbPath, const class FString& Sql);
	static bool OpenCreateDB(const class FString& DbPath, const bool bUseThread);
	static bool Query(const class FString& DbPath, const class FString& Sql, class UKuroSqliteResultSet* ResultSet);
	static int32 QueryValue(const class FString& DbPath, const class FString& Sql, class FString* OutValue);
	static void SetDBKey(const class FString& DBKey);
	static int32 SqliteStatusGetCurrent(const int32 StatusOp);
	static int32 SqliteStatusGetHighWater(const int32 StatusOp, const bool ResetHighWater);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroSqliteLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroSqliteLibrary")
	}
	static class UKuroSqliteLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroSqliteLibrary>();
	}
};
DUMPER7_ASSERTS_UKuroSqliteLibrary;

// Class KuroSqliteBpLib.KuroSqliteResultSet
// 0x0048 (0x0078 - 0x0030)
class UKuroSqliteResultSet final : public UObject
{
public:
	TDelegate<void(bool Success)>                 QueriedCallback;                                   // 0x0030(0x0028)(ZeroConstructor, InstancedReference, NativeAccessSpecifierPublic)
	uint8                                         Pad_58[0x20];                                      // 0x0058(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Release();

	bool GetBigInt(const class FString& Column, int64* Value) const;
	bool GetBool(const class FString& Column, bool* Value) const;
	bool GetBytes(const class FString& Column, struct FArrayBuffer* Value) const;
	bool GetFloat(const class FString& Column, float* Value) const;
	bool GetInt(const class FString& Column, int32* Value) const;
	bool GetString(const class FString& Column, class FString* Value) const;
	bool HasValue() const;
	bool MoveToNext() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroSqliteResultSet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroSqliteResultSet")
	}
	static class UKuroSqliteResultSet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroSqliteResultSet>();
	}
};
DUMPER7_ASSERTS_UKuroSqliteResultSet;

}

