#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NCS_Block_Perfect

#include "Basic.hpp"

#include "BP_CameraShakeAndForceFeedback_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NCS_Block_Perfect.NCS_Block_Perfect_C
// 0x0000 (0x01E0 - 0x01E0)
class UNCS_Block_Perfect_C final : public UBP_CameraShakeAndForceFeedback_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NCS_Block_Perfect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NCS_Block_Perfect_C")
	}
	static class UNCS_Block_Perfect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNCS_Block_Perfect_C>();
	}
};
DUMPER7_ASSERTS_UNCS_Block_Perfect_C;

}

