#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PD_CloudPrefab

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PD_CloudPrefab.PD_CloudPrefab_C
// 0x0008 (0x0198 - 0x0190)
class UPD_CloudPrefab_C final : public UKuroPDCloudPrefab
{
public:
	class UClass*                                 PrefebBP;                                          // 0x0190(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PD_CloudPrefab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PD_CloudPrefab_C")
	}
	static class UPD_CloudPrefab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPD_CloudPrefab_C>();
	}
};
DUMPER7_ASSERTS_UPD_CloudPrefab_C;

}

