#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PD_WeaponLevelMaterialDatas

#include "Basic.hpp"

#include "SWeaponLevelMaterialData_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PD_WeaponLevelMaterialDatas.PD_WeaponLevelMaterialDatas_C
// 0x0050 (0x0088 - 0x0038)
class UPD_WeaponLevelMaterialDatas_C final : public UPrimaryDataAsset
{
public:
	TMap<int32, struct FSWeaponLevelMaterialData> LevelDatas;                                        // 0x0038(0x0050)(Edit, BlueprintVisible, Config)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PD_WeaponLevelMaterialDatas_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PD_WeaponLevelMaterialDatas_C")
	}
	static class UPD_WeaponLevelMaterialDatas_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPD_WeaponLevelMaterialDatas_C>();
	}
};
DUMPER7_ASSERTS_UPD_WeaponLevelMaterialDatas_C;

}

