#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SEffectFloatParameter

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct SEffectFloatParameter.SEffectFloatParameter
// 0x0010 (0x0010 - 0x0000)
struct FSEffectFloatParameter final
{
public:
	class FName                                   Name_2_73B4815B4872FA09388D1E8CAB039F0A;           // 0x0000(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Value_5_1A3845E1458AF3E64BA76BA32FBE27E2;          // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FSEffectFloatParameter;

}

