#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SequenceDialogue

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "SequenceDialogue_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SequenceDialogue.MovieSceneDialogueSubsystem.ShowDialogue
// 0x0038 (0x0038 - 0x0000)
struct MovieSceneDialogueSubsystem_ShowDialogue final
{
public:
	bool                                          bShow;                                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   DialogueID;                                        // 0x0008(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         GuardTime;                                         // 0x0020(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AudioDelay;                                        // 0x0024(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AudioTransitionDuration;                           // 0x0028(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ELanguageAudio                                LanguageType;                                      // 0x002C(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         AutoPlayDelay;                                     // 0x0030(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneDialogueSubsystem_ShowDialogue;

// Function SequenceDialogue.MovieSceneDialogueSubsystem.ShowDialogueAudio
// 0x0020 (0x0020 - 0x0000)
struct MovieSceneDialogueSubsystem_ShowDialogueAudio final
{
public:
	bool                                          bShow;                                             // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 AudioKey;                                          // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AudioTransitionDuration;                           // 0x0018(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneDialogueSubsystem_ShowDialogueAudio;

// Function SequenceDialogue.MovieSceneDialogueSubsystem.TryGetAutoTransformByOffsetTime
// 0x0040 (0x0040 - 0x0000)
struct MovieSceneDialogueSubsystem_TryGetAutoTransformByOffsetTime final
{
public:
	struct FTransform                             OutTrans;                                          // 0x0000(0x0030)(Parm, OutParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	float                                         OffsetTime;                                        // 0x0030(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0034(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_35[0xB];                                       // 0x0035(0x000B)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneDialogueSubsystem_TryGetAutoTransformByOffsetTime;

// Function SequenceDialogue.MovieSceneDialogueSubsystem.GetQteManager
// 0x0008 (0x0008 - 0x0000)
struct MovieSceneDialogueSubsystem_GetQteManager final
{
public:
	class UMovieSceneQteManager*                  ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MovieSceneDialogueSubsystem_GetQteManager;

// Function SequenceDialogue.MovieSceneQteManager.FinishQte
// 0x0004 (0x0004 - 0x0000)
struct MovieSceneQteManager_FinishQte final
{
public:
	int32                                         Id;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MovieSceneQteManager_FinishQte;

// Function SequenceDialogue.MovieSceneQteManager.OnMontageBlendingOut
// 0x0010 (0x0010 - 0x0000)
struct MovieSceneQteManager_OnMontageBlendingOut final
{
public:
	class UAnimMontage*                           Montage;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterrupted;                                      // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneQteManager_OnMontageBlendingOut;

// Function SequenceDialogue.MovieSceneQteManager.UpdateQte
// 0x000C (0x000C - 0x0000)
struct MovieSceneQteManager_UpdateQte final
{
public:
	int32                                         Id;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bProgress;                                         // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ProgressPercentage;                                // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MovieSceneQteManager_UpdateQte;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.AddScalarParameterKey
// 0x0014 (0x0014 - 0x0000)
struct MovieSceneSeqAnimDataSection_AddScalarParameterKey final
{
public:
	class FName                                   InParameterName;                                   // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           InTime;                                            // 0x000C(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InValue;                                           // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_AddScalarParameterKey;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.AddVectorParameterKey
// 0x001C (0x001C - 0x0000)
struct MovieSceneSeqAnimDataSection_AddVectorParameterKey final
{
public:
	class FName                                   InParameterName;                                   // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           InTime;                                            // 0x000C(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                InValue;                                           // 0x0010(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_AddVectorParameterKey;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.GetScalarParameters
// 0x0060 (0x0060 - 0x0000)
struct MovieSceneSeqAnimDataSection_GetScalarParameters final
{
public:
	struct FFrameNumber                           InTime;                                            // 0x0000(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, float>                      Floats;                                            // 0x0008(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0058(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_GetScalarParameters;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.GetVectorParameter
// 0x0020 (0x0020 - 0x0000)
struct MovieSceneSeqAnimDataSection_GetVectorParameter final
{
public:
	class FName                                   InParameterName;                                   // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFrameNumber                           InTime;                                            // 0x000C(0x0004)(Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                Value;                                             // 0x0010(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x001C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_GetVectorParameter;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.RemoveCategory
// 0x0010 (0x0010 - 0x0000)
struct MovieSceneSeqAnimDataSection_RemoveCategory final
{
public:
	class FName                                   InParameterName;                                   // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_RemoveCategory;

// Function SequenceDialogue.MovieSceneSeqAnimDataSection.RemoveScalarParameter
// 0x0010 (0x0010 - 0x0000)
struct MovieSceneSeqAnimDataSection_RemoveScalarParameter final
{
public:
	class FName                                   InParameterName;                                   // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_MovieSceneSeqAnimDataSection_RemoveScalarParameter;

// Function SequenceDialogue.SeqAnimDataInterface.GetAnimDataFloat
// 0x0018 (0x0018 - 0x0000)
struct SeqAnimDataInterface_GetAnimDataFloat final
{
public:
	TArray<struct FNamedCurveValue>               FloatCurveData;                                    // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SeqAnimDataInterface_GetAnimDataFloat;

// Function SequenceDialogue.SeqAnimDataInterface.GetAnimDataVector
// 0x0058 (0x0058 - 0x0000)
struct SeqAnimDataInterface_GetAnimDataVector final
{
public:
	TMap<class FName, struct FVector>             VectorCurveData;                                   // 0x0000(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SeqAnimDataInterface_GetAnimDataVector;

// Function SequenceDialogue.SeqAnimDataInterface.GetSupportGroupNames
// 0x0010 (0x0010 - 0x0000)
struct SeqAnimDataInterface_GetSupportGroupNames final
{
public:
	TArray<class FName>                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SeqAnimDataInterface_GetSupportGroupNames;

// Function SequenceDialogue.SeqAnimDataInterface.SetAnimDataFloat
// 0x0018 (0x0018 - 0x0000)
struct SeqAnimDataInterface_SetAnimDataFloat final
{
public:
	TArray<struct FNamedCurveValue>               FloatCurveData;                                    // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SeqAnimDataInterface_SetAnimDataFloat;

// Function SequenceDialogue.SeqAnimDataInterface.SetAnimDataVector
// 0x0058 (0x0058 - 0x0000)
struct SeqAnimDataInterface_SetAnimDataVector final
{
public:
	TMap<class FName, struct FVector>             VectorCurveData;                                   // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SeqAnimDataInterface_SetAnimDataVector;

// Function SequenceDialogue.SeqAutoTransformInterface.BeginAutoTransform
// 0x0004 (0x0004 - 0x0000)
struct SeqAutoTransformInterface_BeginAutoTransform final
{
public:
	float                                         TimeLength;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SeqAutoTransformInterface_BeginAutoTransform;

// Function SequenceDialogue.SeqQteAnimInterface.GetStateAnimAlpha
// 0x0004 (0x0004 - 0x0000)
struct SeqQteAnimInterface_GetStateAnimAlpha final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SeqQteAnimInterface_GetStateAnimAlpha;

// Function SequenceDialogue.SeqQteAnimInterface.SetStateAnimAlpha
// 0x0004 (0x0004 - 0x0000)
struct SeqQteAnimInterface_SetStateAnimAlpha final
{
public:
	float                                         Alpha;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SeqQteAnimInterface_SetStateAnimAlpha;

}

