#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SFloatPayload

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct SFloatPayload.SFloatPayload
// 0x0010 (0x0010 - 0x0000)
struct FSFloatPayload final
{
public:
	TArray<float>                                 FloatArray_3_C287E81D4FD938F363FB4B9532264861;     // 0x0000(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FSFloatPayload;

}

