#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SFoliageClusteredEffectEntry

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct SFoliageClusteredEffectEntry.SFoliageClusteredEffectEntry
// 0x0018 (0x0018 - 0x0000)
struct FSFoliageClusteredEffectEntry final
{
public:
	class UFoliageType*                           FoliageType_2_AAC77BAA4285BB5E9381359D5EC4578D;    // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEffectClusteredStuffSettings_C*        EffectSetting_5_D7FC350943129146608EA1B72A48674D;  // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumMin_8_3CD5AD914D1404D2C240F183DDDA0F09;         // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NumMax_10_F4A2C209412C086C72B3848FF069E049;        // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FSFoliageClusteredEffectEntry;

}

