#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SVectorArray

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct SVectorArray.SVectorArray
// 0x0010 (0x0010 - 0x0000)
struct FSVectorArray final
{
public:
	TArray<struct FVectorDouble>                  Vectors_3_AA040CBC45AF03F3085A0A808E9BC6C2;        // 0x0000(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FSVectorArray;

}

