#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SWaterEffectGroup

#include "Basic.hpp"

#include "SWaterEffectItem_structs.hpp"


namespace SDK
{

// UserDefinedStruct SWaterEffectGroup.SWaterEffectGroup
// 0x0018 (0x0018 - 0x0000)
struct FSWaterEffectGroup final
{
public:
	float                                         WaterDepth_7_F583B78840B6993AE0DE088887941E47;     // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSWaterEffectItem>              EffectConfig_11_200FB8B949A0725155F4338213E110FB;  // 0x0008(0x0010)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FSWaterEffectGroup;

}

