#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TriggerEffect

#include "Basic.hpp"

#include "TriggerEffect_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class TriggerEffect.KuroTriggerEffect
// 0x0038 (0x0068 - 0x0030)
class UKuroTriggerEffect final : public UObject
{
public:
	bool                                          bUseEffectForThreshold;                            // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         AnalogThreshold;                                   // 0x0031(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMode                                         Mode;                                              // 0x0032(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FFeedbackMode                          FeedbackMode;                                      // 0x0033(0x0002)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVibrationMode                         VibrationMode;                                     // 0x0035(0x0003)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FWeaponMode                            WeaponMode;                                        // 0x0038(0x0003)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FSlopeFeedbackMode                     SlopeFeedbackMode;                                 // 0x003B(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_3F[0x1];                                       // 0x003F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMultiplePositionFeedbackMode          MultiplePositionFeedbackMode;                      // 0x0040(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FMultiplePositionVibrationMode         MultiplePositionVibrationMode;                     // 0x0050(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroTriggerEffect")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroTriggerEffect")
	}
	static class UKuroTriggerEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroTriggerEffect>();
	}
};
DUMPER7_ASSERTS_UKuroTriggerEffect;

// Class TriggerEffect.TriggerEffectBPLibrary
// 0x0000 (0x0030 - 0x0030)
class UTriggerEffectBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void Play(const class APlayerController* PlayerController, const ETriggerEffectSide TriggerSide, const class UKuroTriggerEffect* TriggerEffect);
	static void ResetPadColor(const class APlayerController* PlayerController);
	static void SetPadColor(const class APlayerController* PlayerController, const struct FColor& Color);
	static void SetTriggerEffectState(const class APlayerController* PlayerController, bool bNewState);
	static void TriggerEffectSetFeedbackMode(const class APlayerController* PlayerController, uint8 Position, uint8 Strength, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);
	static void TriggerEffectSetMultipositionFeedbackMode(const class APlayerController* PlayerController, const TArray<uint8>& Strengths, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);
	static void TriggerEffectSetMultipositionVibrationMode(const class APlayerController* PlayerController, uint8 Frequency, const TArray<uint8>& Amplitudes, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);
	static void TriggerEffectSetOffMode(const class APlayerController* PlayerController, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType);
	static void TriggerEffectSetOffModeBothControllers(const class APlayerController* PlayerController);
	static void TriggerEffectSetSlopeFeedbackMode(const class APlayerController* PlayerController, uint8 StartPosition, uint8 EndPosition, uint8 StartStrength, uint8 EndStrength, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);
	static void TriggerEffectSetVibrationMode(const class APlayerController* PlayerController, uint8 Position, uint8 Frequency, uint8 Amplitude, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);
	static void TriggerEffectSetWeaponMode(const class APlayerController* PlayerController, uint8 StartPosition, uint8 EndPosition, uint8 Strength, ETriggerEffectSide TriggerSide, ETriggerEffectControllerType ControllerType, bool bUseEffectForThreshold, uint8 AnalogThreshold);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TriggerEffectBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TriggerEffectBPLibrary")
	}
	static class UTriggerEffectBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTriggerEffectBPLibrary>();
	}
};
DUMPER7_ASSERTS_UTriggerEffectBPLibrary;

}

