#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsActionHandle

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsActionHandle.TsActionHandle_C
// 0x0018 (0x0048 - 0x0030)
class UTsActionHandle_C final : public UObject
{
public:
	class ATsBasePlayerController_C*              PlayerController;                                  // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class FString                                 ActionName;                                        // 0x0038(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void OnPressAction(const struct FKey& key);
	void OnReleaseAction(const struct FKey& key);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsActionHandle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsActionHandle_C")
	}
	static class UTsActionHandle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsActionHandle_C>();
	}
};
DUMPER7_ASSERTS_UTsActionHandle_C;

}

