#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateTurnAdd

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateTurnAdd.TsAnimNotifyStateTurnAdd_C
// 0x0000 (0x0048 - 0x0048)
class UTsAnimNotifyStateTurnAdd_C final : public UKuroAnimNotifyState
{
public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);
	bool K2_NotifyTick(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float FrameDeltaTime);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateTurnAdd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateTurnAdd_C")
	}
	static class UTsAnimNotifyStateTurnAdd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateTurnAdd_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateTurnAdd_C;

}

