#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateAddBuff

#include "Basic.hpp"

#include "ESkillBehaviorBuffTargetType_structs.hpp"
#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateAddBuff.TsAnimNotifyStateAddBuff_C
// 0x0010 (0x0058 - 0x0048)
class UTsAnimNotifyStateAddBuff_C final : public UKuroAnimNotifyState
{
public:
	int64                                         BuffId;                                            // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESkillBehaviorBuffTargetType                  施加目标;                                          // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateAddBuff_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateAddBuff_C")
	}
	static class UTsAnimNotifyStateAddBuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateAddBuff_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateAddBuff_C;

}

