#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyRoleSitDown

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyRoleSitDown.TsAnimNotifyRoleSitDown_C
// 0x0000 (0x0048 - 0x0048)
class UTsAnimNotifyRoleSitDown_C final : public UKuroAnimNotify
{
public:
	bool K2_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyRoleSitDown_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyRoleSitDown_C")
	}
	static class UTsAnimNotifyRoleSitDown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyRoleSitDown_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyRoleSitDown_C;

}

