#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateResponseSignal

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateResponseSignal.TsAnimNotifyStateResponseSignal_C
// 0x0008 (0x0050 - 0x0048)
class UTsAnimNotifyStateResponseSignal_C final : public UKuroAnimNotifyState
{
public:
	int32                                         Signal;                                            // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateResponseSignal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateResponseSignal_C")
	}
	static class UTsAnimNotifyStateResponseSignal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateResponseSignal_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateResponseSignal_C;

}

