#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsBaseCharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ECamp_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ECharacterRenderingType_structs.hpp"
#include "KuroGAS_classes.hpp"
#include "ECharacterDitherType_structs.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsBaseCharacter.TsBaseCharacter_C
// 0x00D0 (0x0750 - 0x0680)
class ATsBaseCharacter_C : public ABaseCharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0680(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNavigationInvokerComponent*            NavigationInvoker;                                 // 0x0688(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UTsCharacterDebugComponent_C*           TsCharacterDebugComponent;                         // 0x0690(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCharRenderingComponent_C*              CharRenderingComponent;                            // 0x0698(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_FightManager_C*                     FightManager;                                      // 0x06A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataTable*                             DtHitEffect;                                       // 0x06A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataTable*                             DtBaseMovementSetting;                             // 0x06B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           BattleSockets;                                     // 0x06B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FName>                           NormalSockets;                                     // 0x06C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UPD_CharacterControllerData_C*          WeaponInEffect;                                    // 0x06D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECharacterRenderingType                       RenderType;                                        // 0x06E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6E1[0x7];                                      // 0x06E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             DtNewBulletDataMain;                               // 0x06E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDataTable*                             DtCharacterPart;                                   // 0x06F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSoftClassPath                         InputComponentClass;                               // 0x06F8(0x0020)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UPrimaryDataAsset*                      FkData;                                            // 0x0718(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEffectModelBase*                       WeaponHideEffect;                                  // 0x0720(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UPrimaryDataAsset*                      CharacterData;                                     // 0x0728(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PhysicsClothSimulateEnable;                        // 0x0730(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          PhysicsClothSimulateDisableOneFrame;               // 0x0731(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	bool                                          CachePoseEnableOneFrame;                           // 0x0732(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper)
	uint8                                         Pad_733[0x1];                                      // 0x0733(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CacheTime;                                         // 0x0734(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UDataTable*                             DtCameraConfig;                                    // 0x0738(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_BasePlatform_C*                     BasePlatform;                                      // 0x0740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	ECamp                                         Camp;                                              // 0x0748(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_749[0x3];                                      // 0x0749(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         EntityId;                                          // 0x074C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TsBaseCharacter(int32 EntryPoint);
	void ReceiveDestroyed();
	void K2_UpdateCustomMovement(float DeltaTime);
	void ReceiveUnpossessed(class AController* OldController);
	void ReceivePossessed(class AController* NewController);
	void K2_OnMovementModeChanged(EMovementMode PrevMovementMode, EMovementMode NewMovementMode, uint8 PrevCustomMode, uint8 NewCustomMode);
	void FightCommand(bool isInAir);
	void Initialize();
	void SetDitherEffect(float dither, ECharacterDitherType ditherType);
	int32 GetEntityId();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsBaseCharacter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsBaseCharacter_C")
	}
	static class ATsBaseCharacter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATsBaseCharacter_C>();
	}
};
DUMPER7_ASSERTS_ATsBaseCharacter_C;

}

