#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsRecordGameplayCue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "KuroAnim_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsRecordGameplayCue.TsRecordGameplayCue_C
// 0x0038 (0x02E8 - 0x02B0)
class ATsRecordGameplayCue_C final : public AKuroRecordEffect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Position0;                                         // 0x02C0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2CC[0x4];                                      // 0x02CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Path;                                              // 0x02D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UBP_GameplayCueBeamDataAsset_C*         BeamData;                                          // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TsRecordGameplayCue(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void OnStop();
	void OnPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsRecordGameplayCue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsRecordGameplayCue_C")
	}
	static class ATsRecordGameplayCue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATsRecordGameplayCue_C>();
	}
};
DUMPER7_ASSERTS_ATsRecordGameplayCue_C;

}

