#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsSeqAnimNotifyAudioEvent

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsSeqAnimNotifyAudioEvent.TsSeqAnimNotifyAudioEvent_C
// 0x0040 (0x0088 - 0x0048)
class UTsSeqAnimNotifyAudioEvent_C final : public UKuroAnimNotify
{
public:
	TSoftObjectPtr<class UAkAudioEvent>           AudioEvent;                                        // 0x0048(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class FName                                   SocketName;                                        // 0x0078(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Follow;                                            // 0x0084(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	bool K2_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsSeqAnimNotifyAudioEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsSeqAnimNotifyAudioEvent_C")
	}
	static class UTsSeqAnimNotifyAudioEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsSeqAnimNotifyAudioEvent_C>();
	}
};
DUMPER7_ASSERTS_UTsSeqAnimNotifyAudioEvent_C;

}

