#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsTowerDefenseEventActor

#include "Basic.hpp"

#include "TsTowerDefenseEventActor_classes.hpp"
#include "TsTowerDefenseEventActor_parameters.hpp"


namespace SDK
{

// Function TsTowerDefenseEventActor.TsTowerDefenseEventActor_C.ExecuteUbergraph_TsTowerDefenseEventActor
// (Final, UbergraphFunction, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATsTowerDefenseEventActor_C::ExecuteUbergraph_TsTowerDefenseEventActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsTowerDefenseEventActor_C", "ExecuteUbergraph_TsTowerDefenseEventActor");

	Params::TsTowerDefenseEventActor_C_ExecuteUbergraph_TsTowerDefenseEventActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TsTowerDefenseEventActor.TsTowerDefenseEventActor_C.OnLevelShown
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ATsTowerDefenseEventActor_C::OnLevelShown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TsTowerDefenseEventActor_C", "OnLevelShown");

	UObject::ProcessEvent(Func, nullptr);
}

}

