#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsUiHotKeyLinkListener

#include "Basic.hpp"

#include "LGUI_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsUiHotKeyLinkListener.TsUiHotKeyLinkListener_C
// 0x0010 (0x0110 - 0x0100)
class UTsUiHotKeyLinkListener_C final : public ULGUIBehaviour
{
public:
	TArray<class AActor*>                         ActorList;                                         // 0x0100(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsUiHotKeyLinkListener_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsUiHotKeyLinkListener_C")
	}
	static class UTsUiHotKeyLinkListener_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsUiHotKeyLinkListener_C>();
	}
};
DUMPER7_ASSERTS_UTsUiHotKeyLinkListener_C;

}

