#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VolcanoMsgChannel

#include "Basic.hpp"


namespace SDK::Params
{

// Function VolcanoMsgChannel.VolcanoPipeWrapper.SendMcBinary
// 0x0010 (0x0010 - 0x0000)
struct VolcanoPipeWrapper_SendMcBinary final
{
public:
	TArray<uint8>                                 bin;                                               // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VolcanoPipeWrapper_SendMcBinary;

// Function VolcanoMsgChannel.VolcanoPipeWrapper.SendMcBinaryWithKey
// 0x0020 (0x0020 - 0x0000)
struct VolcanoPipeWrapper_SendMcBinaryWithKey final
{
public:
	class FString                                 Key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 bin;                                               // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VolcanoPipeWrapper_SendMcBinaryWithKey;

// Function VolcanoMsgChannel.VolcanoPipeWrapper.SendMcString
// 0x0010 (0x0010 - 0x0000)
struct VolcanoPipeWrapper_SendMcString final
{
public:
	class FString                                 msg;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VolcanoPipeWrapper_SendMcString;

}

